nessie.catalog.default-warehouse=warehouse
nessie.catalog.warehouses.warehouse.location=s3://warehouse/

nessie.catalog.service.s3.default-options.endpoint=http://minio:9000
nessie.catalog.service.s3.default-options.region=us-east-1
nessie.catalog.service.s3.default-options.path-style-access=true
nessie.catalog.service.s3.default-options.access-key=urn:nessie-secret:quarkus:s3-creds

s3-creds.name=IldPXM6Sz8RovVr9YFJt
s3-creds.secret=7TevdO8xxBacBj6rv93HUVLDLYpQzxPIWkx9cdhI
