nessie.catalog.default-warehouse=warehouse
nessie.catalog.warehouses.warehouse.location=s3://warehouse/

nessie.catalog.service.s3.default-options.endpoint=http://minio:9000
nessie.catalog.service.s3.default-options.region=us-east-1
nessie.catalog.service.s3.default-options.path-style-access=true
nessie.catalog.service.s3.default-options.access-key=urn:nessie-secret:quarkus:s3-creds

# Overridden via env vars S3_CREDS_NAME and S3_CREDS_SECRET
s3-creds.name=placeholder
s3-creds.secret=placeholder
